#
# Put user-defined variables here
#

KEXTNAME?=				procfs
KEXTVERSION?=			1.0.0
KEXTBUILD?=				1
FSNAME?=				$(KEXTNAME)
FSVERSION?=				$(KEXTVERSION)
FSBUILD?=				$(KEXTBUILD)
BUNDLEDOMAIN?=			com.beako.filesystems
COPYRIGHT?= 			"Copyright © 2022 Sunneva Jonsdottir, All rights reserved."
SIGNCERT?= -
